### PR TITLE
Kwami Graphics Update

### PR DESCRIPTION
**Pull request by kwamistudios**
Added the CSS rendered logo to the navigation bar, created CSS files for the logo and the gameroom. Integrated the Kwami CF2 Demo graphics into the JavaScript, with modifications to use PIXI as the drawing engine. All JavaScript files updated to use a variation of the WikiMedia whitespace conventions.

### CODE REVIEW

**Comment by gaogaotiantian** [comment]
I like the overall code quality, it's decent. However, there are a couple of things you need to modify after I merge it in. 

First of all, ```cellSize``` needs to be 32px. It does not mean the rounded rectangle needs to be 32px, but the background, aka the area a cell actually takes should be 32px * 32px. We need to adjust the stage based the display size, but the cell size before adjusting should be 32px. The reason is that I want to do some pixel art for buildings, and the most reasonable size is 32px * 32px. It would make it much easier to put the picture on the cell if the cell size is the same. I believe currently you are doing some math to make it actually 32px for each cell. You can definitely do math like that, but I want the global variable to be clearly 32 and do math on the size you draw the rounded cell.

Secondly, ```ID_COLORS``` should be an array initialized with values instead of dynamically pushed in. It's better to make a table than pushing it during initialization. But yes, you can push the random color in if there are too many IDs.

As for ```draw_game```, I believe you did an internal animation loop for now. I think PIXI has some built-in animation loop to work on. Since we do not have any animations for now, we can either trigger the drawing when we receive data, or keep it as it is, but I may want to use the PIXI animiation system in the future. Currently the ```draw_game``` function runs too frequently and it's unnecessary. Also I think you should check both width and height overflow?

The last thing is the pixel art logo. I like it, but it's not okay to have 400 lines of ```<div>``` code in ```narbar.html``` and it's not the best practice to do that many lines in css. It would be nice to actually build a png image and use that. 

I think we got a really good start and maybe you could fix the stuff I mentioned above.

**Comment by kwamistudios** [comment]
Thank you for your feedback. Here's our change notes:

We updated the `cellSize` game constant to be 32px, for the easy transition into a spritesheet in the future.

`ID_COLORS` has been updated to be an inline declaration, rather than being dynamically generated.

`draw_game` will remain unchanged, for now. As far as we are aware, the math works out for the height/width check. Bootstrap already bounds the width, and the resize only applies if the width is greater than the height, so it should be properly bounded already. The frequency of the `draw_game` function is not abnormal for a `requestAnimationFrame` call, and we plan on using it in conjunction with the `gameData[ "info" ][ "round_time" ]` to create smooth animations between rounds when players capture cells. As far as we have researched, there is no "proper" convention for PIXI game loops other than the ticker, so `requestAnimationFrame` should still be a valid solution.

The pixel art logo has been converted to a PNG file, but we still would like to find a way to vectorize it instead, so that such a simplistic design isn't wasting bandwidth. Perhaps a CDN could be another alternative.

**Comment by kwamistudios** [comment]
Changelog:

We limited the line length of ID_COLORS and split it into three lines, instead of one long one.

We removed the #header from gameroom.css, but it should not have had any affect on the navbar in any case. It was an artifact from our demo code that we forgot to remove, but the navbar should be consistent for every page including the game room. We verified this already before the updates on our test server, though it is possible we missed something.

Sounds good on the logo. We were thinking of using the CSS rendering to easily do lossless resizing for different page sizes, but it isn't necessary for the current interface. 

Thank you again for your feedback, and we would definitely be interested in talking about future plans for CFII.

**Comment by kwamistudios** [comment]
Alright, we committed that last change

**Pull request merged**
